publisher_headings:
  - 'U.S. G.P.O., '
  - 'Government Printing Office,'
  - 'For sale by the Supt. of Docs., U.S. Govt. Print. Off.,'
  - 'U.S. G.P.O. :'
  - 'For sale by the Supt. of Docs., U.S. G.P.O.,'
  - 'U.S. Govt. Print. Off.,'
  - 'distributed by the Office of Scientific and Technical Information, U.S. Dept. of Energy,'
  - 'For sale by the U.S. G.P.O., Supt. of Docs., Congressional Sales Office,'
  - 'United States. Dept. of Energy ;'
  - 'National Technical Information Service, distributor,'
  - 'For sale by the Supt. of Docs., Congressional Sales Office, U.S. G.P.O.,'
  - 'National Aeronautics and Space Administration ;'
  - 'U.S. Dept. of the Interior, U.S. Geological Survey,'
  - 'U.S. General Accounting Office,'
  - 'U.S. Geological Survey,'
  - 'U.S. Dept. of Commerce, Bureau of the Census :'
  - 'U.S. Dept. of Education, Office of Educational Research and Improvement, Educational Resources Information Center,'
  - 'G.P.O.,'
  - 'For sale by the National Technical Information Service,'
  - 'U.S. Govt. Accountability Office,'
  - 'U.S. Dept. of the Interior, U.S. Geological Survey ;'
  - 'Congressional Research Service, Library of Congress,'
  - 'For sale by the Supt. of Docs., U.S. G.P.O. [Congressional Sales Office],'
  - 'Govt. Print. Off.,'
  - 'For sale by Supt. of Docs., U.S. G.P.O.,'
  - 'Supt. of Docs., U.S. G.P.O., distributor,'
  - 'U.S. Dept. of the Interior, Bureau of Mines,'
  - 'Federal Emergency Management Agency,'
  - 'U.S. Dept. of Agriculture,'
  - 'National Aeronautics and Space Administration,'
  - 'for sale by the National Technical Information Service,'
  - 'Headquarters, Dept. of the Army,'
  - 'For sale by the National Technical Information Service],'
  - 'For sale by the Supt. of Docs., U.S. Govt. Print. Off.,'
  - 'U.S. G.P.O.'
  - 'For sale by the Supt. of Docs., U.S. G.P.O., [Congressional Sales Office],'
  - 'For sale by the U.S. G.P.O., Supt. of Docs.,'
  - 'Govt. print. off.,'
  - 'United States. Dept. of Defense ;'
  - 'Central Intelligence Agency,'
  - 'Dept. of State :'
  - 'National Technical Information Service [distributor,'
  - 'for sale by the Supt. of Docs., U.S. Govt. Print. Off.,'
  - 'National Aeronautics and Space Administration, Langley Research Center ;'
  - 'U.S. Dept. of Commerce, Economics and Statistics Administration, Bureau of the Census :'
  - 'U.S. Government Accountability Office,'
  - 'U.S. International Trade Commission,'
  - 'Dept. of the Treasury, Internal Revenue Service,'
  - 'United States. Dept. of Energy. Office of Energy Research ;'
  - 'U.S. Govt. print. off.,'
  - 'National Renewable Energy Laboratory,'
  - 'U.S. Dept. of the Interior, Geological Survey,'
  - '[Supt. of Docs., U.S. G.P.O., distributor,'
  - 'U.S. Dept. of State,'
  - 'U.S. Geological Survey ;'
  - 'National Aeronautics and Space Administration, Scientific and Technical Information Branch ;'
  - 'Smithsonian Institution Press,'
  - 'Available from National Technical Information Service,'
  - 'U.S. Dept. of Agriculture, Forest Service,'
  - 'Lawrence Berkeley National Laboratory ;'
  - 'Federal Emergency Management Agency'
  - 'General Accounting Office,'
  - 'Los Alamos National Laboratory ;'
  - 'U. S. Govt. Print. Off.,'
  - 'National Aeronautics and Space Administration, Langley Research Center,'
  - 'U.S. Dept. of Agriculture, Economic Research Service,'
  - 'U.S. Dept. of Agriculture, Forest Service, Pacific Northwest Research Station,'
  - 'National Aeronautics and Space Administration'
  - 'State Department'
  - 'Federal Financial Institutions Examination Council,'
  - 'Oak Ridge National Laboratory. ;'
  - 'U.S. Dept. of the Interior, Geological Survey ;'
  - 'U.S. Environmental Protection Agency,'
  - 'U.S. G.P.O. ;'
  - 'Federal Emergency Management Agency, Federal Insurance Administration,'
  - 'U.S. Dept. of Labor, Bureau of Labor Statistics,'
  - 'U.S. Dept. of Commerce, Economics and Statistics Administration, U.S. Census Bureau,'
  - 'Dept. of the Interior, U.S. Geological Survey ;'
  - 'Dept. of Housing and Urban Development, Federal Insurance Administration,'
  - 'Historical Records Survey,'
  - 'Transportation Research Board, National Research Council,'
